addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.9.2")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.10")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")